### PR TITLE
Add executeGroovyScriptWithCommit, Add shortcuts F5 for running commands, Add clearCache, Add fsql format

### PR DESCRIPTION
**Pull request by leoiii12**
…ferent commands

### CODE REVIEW

**Comment by mojo2012** [comment]
Thx for the PR. I merged, but was not yet able to test it. I'll try to setup a local hybris install and as soon as I tested it, I will deploy the new version.
Any chance you want to take of the project as a maintainer? I'm currently not working with hybris (probably never will again :-D).

**Comment by leoiii12** [comment]
Our company just found this great plugin and is willing to add more features to it.

**Comment by mojo2012** [comment]
I moved the repo to a separate organization and added you as a collaborator. If you want to professionalize the extension, we should setup a proper CI (travis?) and a nice website. Drop me a PM on discord (same username as on github).
Also, can you verify that the current master works? If yes, then I will release a new version)

**Comment by leoiii12** [comment]
https://discordapp.com? Can't add you. It requires four digit tag.
Not aiming for professionalize. Just start using in our company.

**Comment by mojo2012** [comment]
mojo2012#2582

**Pull request merged**
